### ISSUE TITLE
5V instead of 3.3V?

### ISSUE THREAD

**Issue by optikfluffel** [tricoos/m135-lua#1]
Hey there 👋 

The [specs of the MQ135](https://www.futurlec.com/Datasheet/Sensor/MQ-135.pdf) say it needs `5V` to operate.
Is there some kind of lua-magic to cope for that? 🤔
My understanding was that I needed some kind of voltage divider, to power the sensor with `5V` and then bring down the output signal to `3.3V` before putting it into the analog input of my NodeMCU.

Greetings from Berlin 🌤

**Comment by baebsndeep** [comment]
I think that's typo in the README.
Use VCC --> 5V.
Tested functional using VCC --> 5V today.
Let me know if you run into issues :)
